name: PlexKillstreaks
version: 1.0.0
main: com.plexdev.plexkillstreaks.PlexKillstreaks
api-version: '1.21'
author: Plex
description: A lightweight and fully configurable killstreak plugin for Paper 1.21+
website: https://github.com/applexDev/PlexKillstreaks

commands:
  streak:
    description: View your current and highest killstreak
    usage: /streak
    aliases:
      - streaks
    permission: plexkillstreaks.streak
    permission-message: "You don't have permission to use this command."

  streakreload:
    description: Reload the Plex Killstreaks configuration
    usage: /streakreload
    permission: plexkillstreaks.reload
    permission-message: "You don't have permission to use this command."

permissions:
  plexkillstreaks.streak:
    description: Allows the player to view their killstreak
    default: true

  plexkillstreaks.reload:
    description: Allows the player to reload the Plex Killstreaks configuration
    default: op

softdepend:
  - PlaceholderAPI